name: Automated Pull

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Config git creds
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@coinstats.app"
          
      - name: Pull the changes from main
        run: | 
          git fetch
          git switch dev
          git pull
          git pull origin -s recursive -X theirs main --no-rebase --allow-unrelated-histories
          git push 
