name: Automated Pull

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #  with:
      #    ref: 'dev'
          
      - name: Pull the change from main
        run: | 
          git fetch
          git checkout dev
          git pull
          git pull origin main --rebase
          git push 
