name: Automated Pull

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
          
      - name: Pull the change from main
        run: | 
          git pull origin main
          git push origin dev
