name: Automated Pull

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: github.base_ref
        run: echo "github.base_ref"
        
      - name: github.base_ref
        run: echo "github.head_ref"
