name: Automated Pull

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
          
      - name: Pull the changes from main
        run: | 
          git fetch
          git switch dev
          git pull
          git pull origin main --no-rebase --allow-unrelated-histories
          git push 
